[functions.upload-book-cover]
verify_jwt = false

[functions.create-book]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.get-access-token]
verify_jwt = false

[functions.read-book]
verify_jwt = false

[functions.upload-book-pdf]
verify_jwt = false

[functions.subscribe-newsletter]
verify_jwt = false

[functions.send-newsletter-update]
verify_jwt = false
